### PR TITLE
Updated UI of header and footer

### PR DESCRIPTION
**Pull request by Shaun04**
I edited the header to be in the center of the page. The footer has some minor UI changes. The screenshots below show the edits.
footer
header

### CODE REVIEW

**Comment by adrelanos** [comment]
Looks a lot better as per screenshot. Will test.

**Comment by adrelanos** [comment]
Looks great! Thank you!

**Comment by Shaun04** [comment]
@adrelanos Thank you. As this was my first contribution to an open source project was everything done properly?

**Comment by adrelanos** [comment]
Welcome to the community! Everything Perfect! :)

**Comment by Shaun04** [comment]
Thank you so much.

**Pull request merged**
